Repository Dev-FE-1/Toy_Project_II_team2, pull requests merged in 2024-08, with the labels that each got.

#36 [Feature]직원페이지퍼블리싱 및 기능추가
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/components/Select.tsx
  src/pages/Payroll/Payroll-History.tsx
Labels: feature

#38 [feature] 직원리스트 페이지네이션 추가
  package-lock.json
  package.json
  src/components/EmployeeList/DaysOfWeek.tsx
  src/components/EmployeeList/EmployeeAdd.tsx
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/EmployeeList/WorkTimePicker.tsx
  src/components/EmployeeList/bankSelect.tsx
  src/components/Select.tsx
  src/components/bankSelect.tsx
  src/components/pagination.tsx
  src/pages/EmployeeList/EmployeeAdd.tsx
  src/pages/EmployeeList/EmployeeList.tsx
Labels: feature

#39 [Feature]firebase members안에 collection가져오는훅생성
  src/Hooks/useUserData.tsx
Labels: feature

#44 [Feature] 로그인 페이지 퍼블리싱 수정
  public/images/workcheck_logo_signin.png
  public/images/workcheck_logo_signin.svg
  src/App.tsx
  src/components/Button.tsx
  src/pages/Signin.tsx
Labels: feature

#45 [Feature] firebase 데이터로 급여내역페이지 세팅
  src/API/Firebase/GetUserData.tsx
  src/Hooks/useUserData.tsx
  src/components/PayrollList/ApprovalModal.tsx
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/pages/Payroll/Payroll-History.tsx
Labels: feature

#46 [Feature] 급여내역페이지 firebase crud 작업
  src/API/Firebase/CreatePayrollCorApp.tsx
  src/API/Firebase/DeleteSalaryCorrection.tsx
  src/API/Firebase/UpdatePayrollCorApp.tsx
  src/API/Firebase/UpdatePayrollData.tsx
  src/components/PayrollList/ApprovalModal.tsx
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/pages/Payroll/Payroll-History.tsx
Labels: feature

#48 [Feature]일정관리 db연동 및 CRUD
  src/API/Firebase/AddCalendarEvent.tsx
  src/API/Firebase/DeleteCalendarEvent.tsx
  src/API/Firebase/UpdateCalendarEvent.tsx
  src/components/Calendar/Calendar-add.tsx
  src/components/Calendar/Calendar-detail.tsx
  src/components/Calendar/Calendar.tsx
Labels: feature

#49 [Feature] redux store생성
  src/API/Firebase/UpdatePayrollData.tsx
  src/Reducers/employeeSalarySlice.ts
  src/main.tsx
  src/pages/Payroll/Payroll-History.tsx
  src/store.ts
Labels: feature

#51 [feature] 직원리스트 firebase 연결, 삭제 구현, 수정 구현
  src/API/Firebase/AddEmployeeList.tsx
  src/API/Firebase/DeleteEmployeeList.tsx
  src/API/Firebase/GetEmployeeData.tsx
  src/API/Firebase/UpdateEmployeeList.tsx
  src/components/Button.tsx
  src/components/EmployeeList/DaysOfWeek.tsx
  src/components/EmployeeList/EmployeeAdd.tsx
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/EmployeeList/bankSelect.tsx
  src/components/Modal.tsx
  src/components/pagination.tsx
  src/globalStyle.tsx
  src/pages/EmployeeList/EmployeeList.tsx
Labels: feature

#53 [Feature] ModalSlice작성
  src/Reducers/ModalSlice.ts
  src/Reducers/employeeSalarySlice.ts
  src/components/PayrollList/ApprovalModal.tsx
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/main.tsx
  src/pages/Payroll/PayrollHistory.tsx
  src/store.ts
Labels: feature

#54 [feature] 로딩애니메이션 추가
  src/components/LodingAnimation.tsx
  src/pages/EmployeeList/EmployeeList.tsx
Labels: feature

#55 [Feature] EmployeeSalarySlice 작성
  src/Reducers/employeeSalarySlice.ts
  src/components/Calendar/Calendar.tsx
  src/pages/Payroll/PayrollHistory.tsx
  src/store.ts
Labels: feature

#58 [Feature] 급여내역페이지 로딩애니메이션적용
  src/pages/Payroll/PayrollHistory.tsx
  tsconfig.app.json
Labels: feature

#60 [Feature] 일정관리페이지 redux
  package-lock.json
  package.json
  src/API/Firebase/AddCalendarEvent.tsx
  src/Reducers/CalendarEventSlice.ts
  src/components/Calendar/Calendar-add.tsx
  src/components/Calendar/Calendar-delete.tsx
  src/components/Calendar/Calendar-detail.tsx
  src/components/Calendar/Calendar.tsx
  src/pages/EmployeeList/EmployeeScheduleRequests.tsx
  src/store.ts
Labels: feature

#61 [Feature] 404페이지 작업 및 파비콘 추가
  index.html
  public/icons/workcheckFavicon.ico
  src/pages/Error.tsx
Labels: feature

#62 [Feat] 홈 컴포넌트 추가 및 전반적 스타일링과 로직 수정
  .eslintrc.cjs
  package-lock.json
  package.json
  public/images/Polygon 1.svg
  public/images/Polygon 2.svg
  public/images/firework.png
  src/API/Firebase/AddCalendarEvent.tsx
  src/API/Firebase/CreatePayrollCorApp.tsx
  src/API/Firebase/DeleteCalendarEvent.tsx
  src/API/Firebase/DeleteEmployeeList.tsx
  src/API/Firebase/DeleteSalaryCorrection.tsx
  src/API/Firebase/GetCorrectionData.tsx
  src/API/Firebase/GetEmployeeData.tsx
  src/API/Firebase/GetUserCalendarEvents.tsx
  src/API/Firebase/GetUserData.tsx
  src/API/Firebase/Payday.tsx
  src/API/Firebase/UpdateCalendarEvent.tsx
  src/API/Firebase/UpdateEmployeeList.tsx
  src/API/Firebase/UpdatePayrollCorApp.tsx
  src/API/Firebase/UpdatePayrollData.tsx
  src/Reducers/CalendarEventSlice.ts
  src/Reducers/EmployeeSalarySlice.tsx
  src/components/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/Header.tsx
  src/components/Home/Dday.tsx
  src/components/Home/Payday.tsx
  src/components/Home/PayrollAbstract.tsx
  src/components/Home/PayrollCorrection.tsx
  src/globalStyle.tsx
  src/main.tsx
  src/pages/EmployeeList/EmployeeList.tsx
  src/pages/EmployeeList/EmployeeScheduleRequests.tsx
  src/pages/Home.tsx
  src/pages/Payroll/PayrollHistory.tsx
  src/pages/ProtectedRoute.tsx
  src/pages/Schedule-Manage/Schedule-Manage.tsx
  src/store.tsx
Labels: feature

#63 [Feature] isAdmin상태를상수로수정, css포인터추가
  src/components/PayrollList/SalaryList.tsx
  src/pages/Payroll/PayrollHistory.tsx
Labels: feature

#66 [Feature] type 추가 지정
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SpacificationModal.tsx
Labels: feature

#67 [Feature] 급여내역페이지 css수정
  src/components/PayrollList/SalaryList.tsx
  src/pages/Payroll/PayrollHistory.tsx
Labels: feature

#70 [Featuer] 일정관리페이지 로딩스피너 적용
  src/components/Calendar/Calendar-add.tsx
  src/components/Calendar/Calendar-detail.tsx
  src/components/Calendar/Calendar.tsx
Labels: feature

#73 [docs] Readme 작성
  README.md
Labels: documentation

#75 [feature] 직원수정 시간컴포넌트 수정완료
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/Select.tsx
Labels: feature

#79 [Refactor] 기능 수정 및 점검
  server/index.ts
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/pages/Payroll/PayrollHistory.tsx
  src/store.ts
Labels: feature

#80 [Feat] 로딩 애니메이션 관련 커스텀 훅 추가
  src/CustomHooks/UseAggregateLoading.tsx
  src/CustomHooks/UseFetchWithLoading.tsx
  src/CustomHooks/UseLoading.tsx
Labels: feature

#81 [fix] css 수정
  public/images/workcheck-logo-header.svg
  src/components/Calendar/Calendar.tsx
  src/components/Header.tsx
  src/components/Home/PayrollCorrection.tsx
  src/pages/Home.tsx
  src/pages/Signin.tsx
Labels: feature

#82 [Bug] 일정관리 이벤트 수정 버그 픽스
  src/API/Firebase/GetUserCalendarEvents.tsx
  src/API/Firebase/UpdateCalendarEvent.tsx
  src/Reducers/CalendarEventSlice.ts
Labels: bug

#84 [docs] readme update (#57)
  README.md
Labels: documentation

#85 [fix] 캘린더, 직원 홈 디데이컴포넌트 위치 css 수정
  src/components/Calendar/Calendar-add.tsx
  src/components/Calendar/Calendar-detail.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/Dday.tsx
  src/components/PayrollList/SalaryList.tsx
  src/pages/Payroll/PayrollHistory.tsx
Labels: feature

#86 [Refactor] 코드수정 및 ts파일로 복구
  src/API/Firebase/AddCalendarEvent.ts
  src/API/Firebase/AddEmployeeList.ts
  src/API/Firebase/CreatePayrollCorApp.ts
  src/API/Firebase/DeleteCalendarEvent.ts
  src/API/Firebase/DeleteEmployeeList.ts
  src/API/Firebase/DeleteSalaryCorrection.ts
  src/API/Firebase/Firebase.ts
  src/API/Firebase/Firebase_Config.ts
  src/API/Firebase/GetCorrectionData.ts
  src/API/Firebase/GetEmployeeData.ts
  src/API/Firebase/GetUserCalendarEvents.ts
  src/API/Firebase/GetUserData.ts
  src/API/Firebase/Payday.ts
  src/API/Firebase/UpdateCalendarEvent.ts
  src/API/Firebase/UpdateEmployeeList.ts
  src/API/Firebase/UpdatePayrollCorApp.ts
  src/API/Firebase/UpdatePayrollData.ts
  src/Reducers/CalendarEventSlice.ts
  src/Reducers/EmployeeSalarySlice.ts
  src/Reducers/ModalSlice.ts
  src/components/Calendar/Calendar.tsx
  src/components/EmployeeList/EmployeeAdd.tsx
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/Home/Payday.tsx
  src/components/Home/PayrollCorrection.tsx
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/main.tsx
  src/pages/EmployeeList/EmployeeList.tsx
  src/pages/Payroll/PayrollHistory.tsx
  src/pages/Signin.tsx
  src/store.ts
  src/store.tsx
Labels: feature

#88 [Refector] 급여수정시 수정되지않으면 버튼이 유지되도록 수정
  src/API/Firebase/DeleteSalaryCorrection.ts
  src/API/Firebase/UpdatePayrollCorApp.ts
  src/API/Firebase/UpdatePayrollData.ts
  src/components/PayrollList/PayList.tsx
  src/components/PayrollList/SalaryList.tsx
  src/components/PayrollList/SpacificationModal.tsx
  src/pages/Payroll/PayrollHistory.tsx
Labels: feature

#92 [Refactor] 직원리스트 페이지 리팩토링
  package-lock.json
  package.json
  src/API/Firebase/AddEmployeeList.ts
  src/API/Firebase/DeleteEmployeeList.ts
  src/API/Firebase/GetEmployeeData.ts
  src/API/Firebase/UpdateEmployeeList.ts
  src/components/EmployeeList/DaysOfWeek.tsx
  src/components/EmployeeList/EmployeeAdd.tsx
  src/components/EmployeeList/EmployeeSpecificModal.tsx
  src/components/EmployeeList/WorkTimePicker.tsx
  src/components/EmployeeList/bankSelect.tsx
  src/components/LodingAnimation.tsx
  src/components/Modal.tsx
  src/components/Select.tsx
  src/components/pagination.tsx
  src/pages/EmployeeList/EmployeeList.tsx
  src/pages/EmployeeList/EmployeeScheduleRequests.tsx
Labels: feature

#91 [Refactor] 일정관리페이지 리펙토링
  src/API/Firebase/AddCalendarEvent.ts
  src/API/Firebase/DeleteCalendarEvent.ts
  src/API/Firebase/GetUserCalendarEvents.ts
  src/API/Firebase/UpdateCalendarEvent.ts
  src/Reducers/CalendarEventSlice.ts
  src/components/Calendar/Calendar-add.tsx
  src/components/Calendar/Calendar-delete.tsx
  src/components/Calendar/Calendar-detail.tsx
  src/components/Calendar/Calendar.tsx
Labels: feature
